### ISSUE TITLE
Cannot build with rustc 1.68.0

### ISSUE THREAD

**Issue by TerminalHash** [OpenGMK/OpenGMK#130]
I'm using Artix Linux on workstation with rustc 1.68.0.

> error: linking with `cc` failed: exit status: 1
>   |
>   = note: LC_ALL="C" PATH="/usr/lib64/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-m64" "/tmp/rustcGyZt1N/symbols.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.38x96hhytjczbihb.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.addr2line-132ff156f03de661.addr2line.dec7d867-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.adler-4a85b09a8fbf4a23.adler.92d9d147-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.adler-c3a7b2fb24991119.adler.66cafa0a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.adler32-f76762ed1519b4f5.adler32.5b376f60-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.ahash-f86029980f1d0a0c.ahash.20ed7e51-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.alloc-9d13b2ea26b3f2b6.alloc.32832d00-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.bincode-85a2a71be0c7962b.bincode.46296482-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.bitflags-ec70bfd457981ad6.bitflags.f5c62a37-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.bytemuck-a4f5fc7dacdd9c41.bytemuck.37d6c6b3-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.byteorder-a2fab9c8a128988c.byteorder.752f835b-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.cfg_if-b8d1a8b42988e322.cfg_if.d756a9b0-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.cfg_if-dea218306979b83e.cfg_if.0f01dcb2-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.chlorine-306d0f1e17a673aa.chlorine.084f2acb-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.cimgui_sys-9fac923c4b004d42.cimgui_sys.39537853-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.color_quant-eac0376ac820a477.color_quant.76df489b-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.core-47d41ae69362fe4c.core.0dfe3cef-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.crc32fast-44f44c7b03d457a7.crc32fast.e0f587ac-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.crossbeam_channel-560dee711ac249a3.crossbeam_channel.63d6e357-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.crossbeam_deque-c272ab63cf72a301.crossbeam_deque.65ecfe52-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.crossbeam_epoch-4cc78afb6a40c0b0.crossbeam_epoch.9b920476-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.crossbeam_utils-731fe0c856816ba9.crossbeam_utils.36b47eeb-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.deflate-1ceb65ba28827304.deflate.cdfc936e-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.dlv_list-4bd523dc8ba250f8.dlv_list.c07f791b-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.either-41849781c65cdce4.either.51dd808a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.encoding_rs-d0c30d2427923b06.encoding_rs.c1894d60-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.flate2-9b511b9763fdaccb.flate2.7eee181e-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.getopts-7039eee67f876243.getopts.304c8561-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.getrandom-76790e3655fb0176.getrandom.03d53dcb-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.gif-cb7e22de1b96bcf4.gif.0402267a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.gimli-eed2f634e8f31ae7.gimli.290ceebe-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.glob-fac3050501e3a390.glob.e5d13936-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.gm8emulator.07548c36-cgu.0.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.gm8exe-26f5adb09670ce9a.gm8exe.6ab8afeb-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.gml_parser-c0af109424968c4e.gml_parser.3934331a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.hashbrown-61440d9b5f47ca55.hashbrown.43a9a3dc-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.hashbrown-b6eb9e86de138e38.hashbrown.f39fb0e8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.hashbrown-bf2bb568f8146464.hashbrown.9072ed2e-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.hex-27d95244e9cc664a.hex.d096e3f8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.image-ac85c22d37a70d27.image.11fc1d52-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.indexmap-41cccc0ded14ebd1.indexmap.9c2e91fb-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.ini-619abbc6f507cfd8.ini.d20f4144-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.jpeg_decoder-9a54a317b48631a1.jpeg_decoder.476c3f34-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.libc-3f95228f9e4efa9f.libc.43ae28e9-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.libc-71aa623cc3899c13.libc.622deae0-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.libsoundio_sys-09bce83bdb19f39b.libsoundio_sys.38df21f0-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.libz_sys-3063ad176352318d.libz_sys.1a25ef38-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.lock_api-3c31bad43598d462.lock_api.b434b468-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.lzzzz-dec97b35e3725532.lzzzz.b2218746-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.memchr-b8c0b8b77b596206.memchr.6ad75c31-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.memoffset-8c1239ea3455e26b.memoffset.59aba239-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.memoffset-90a953c33c1a797d.memoffset.709fc6c7-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.miniz_oxide-08551a6864b58c3d.miniz_oxide.bb8ff9f8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.miniz_oxide-7159d89ebc5b8cdd.miniz_oxide.8108a46a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.miniz_oxide-8ed27629f6cbf693.miniz_oxide.7e13ddb7-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_cpus-25c81dd06848facb.num_cpus.4617e7d4-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_integer-08c7487aa7bd6d66.num_integer.23f0a73b-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_iter-96ba235b9d35f36d.num_iter.b518e44c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_rational-ea2d70e8973c9a3a.num_rational.ff420c9a-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_threads-4812b8d467e6b1dc.num_threads.703543e8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.num_traits-e1b4e304b9f27954.num_traits.a0323987-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.object-caec54db7c903860.object.e81d0696-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.once_cell-32bba9ad844aec2a.once_cell.1d3c7197-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.ordered_multimap-9781d1de23d6f85a.ordered_multimap.68ca05b1-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.panic_unwind-4849f658ef0b127c.panic_unwind.93ac06d2-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.parking_lot-c2bcf11d356def7f.parking_lot.e418bc40-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.parking_lot_core-4ffc13fbe3a3261e.parking_lot_core.0a5d0da3-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.phf-18faf5af606fbf88.phf.5d1fca93-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.phf_shared-02ebe4182cc37d54.phf_shared.f590baad-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.png-09049e78d28445de.png.77c69cb7-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.ppv_lite86-da3da3d27af814fe.ppv_lite86.558eafce-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.ramen-ef41a2bf10aeb07d.ramen.3297664f-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rand-9dd1eb17ef5e577b.rand.e6e418fc-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rand_chacha-38f504acbf513f7e.rand_chacha.a6385131-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rand_core-7de864014d8a61c2.rand_core.413ae94c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rayon-1c93f64fc934f4d8.rayon.51484d9e-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rayon_core-730e66abc8f17257.rayon_core.d5bc5d5c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rect_packer-b9807ce2974fff95.rect_packer.9129c1ad-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rmp3-bbb195afb26fec01.rmp3.82059434-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rustc_demangle-8ef01f6e50e9c860.rustc_demangle.57bcc82c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rustc_std_workspace_alloc-89153952bb85c94a.rustc_std_workspace_alloc.6a928bdf-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.rustc_std_workspace_core-9046737136dcb1d1.rustc_std_workspace_core.0ba034f8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.scoped_threadpool-72409a4474af30a0.scoped_threadpool.80784118-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.scopeguard-64aef7763d360727.scopeguard.b20dee79-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.serde-5c2c4a2a9711ba49.serde.be057647-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.siphasher-3196e0c234a3f659.siphasher.cebd93b8-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.smallvec-d5d38d7ecd318cc3.smallvec.e43b619d-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.std-097c13f657f78ee9.std.f4dbe29b-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.std_detect-d59dcd488ee23498.std_detect.89d652ab-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.tiff-7cbd652dcebcdfcf.tiff.f6f6dbd2-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.time-d4400984bf88a53e.time.09e22783-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.udon-14f170521629a656.udon.b9e5fe8c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.unicode_width-1215d613e19e8ff5.unicode_width.df03f125-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.unwind-3aa3856d555cdbd1.unwind.5a51c29c-cgu.0.rcgu.o.rcgu.o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39.weezl-357812280c230489.weezl.7807d075-cgu.0.rcgu.o.rcgu.o" "-Wl,--as-needed" "-L" "/home/terminalhash/build/OpenGMK/target/release/deps" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/cimgui-sys-fe9cace083611e57/out" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/cimgui-sys-fe9cace083611e57/out" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/libz-sys-2627c0f81f27b4fd/out/lib" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/lzzzz-e805978cc25b9b47/out" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/rmp3-bd3c228843d5abf4/out" "-L" "/usr/lib" "-L" "/usr/lib" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/libsoundio-sys-4c3b8bbc1d8ad8c1/out/lib64" "-L" "/home/terminalhash/build/OpenGMK/target/release/build/libsoundio-sys-4c3b8bbc1d8ad8c1/out/lib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-lGL" "-Wl,-Bstatic" "/tmp/rustcGyZt1N/libcimgui_sys-9fac923c4b004d42.rlib" "/tmp/rustcGyZt1N/liblzzzz-dec97b35e3725532.rlib" "/tmp/rustcGyZt1N/librmp3-bbb195afb26fec01.rlib" "/tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib" "/tmp/rustcGyZt1N/liblibz_sys-3063ad176352318d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3248f0e5ea4f301a.rlib" "-Wl,-Bdynamic" "-lasound" "-lpulse" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/terminalhash/build/OpenGMK/target/release/deps/gm8emulator-6703c2c76000dc39" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
>   = note: /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `instream_destroy_jack':
>           jack.c:(.text.instream_destroy_jack+0xc): undefined reference to `jack_client_close'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `outstream_destroy_jack':
>           jack.c:(.text.outstream_destroy_jack+0xc): undefined reference to `jack_client_close'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `instream_open_jack':
>           jack.c:(.text.instream_open_jack+0x75): undefined reference to `jack_client_open'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x97): undefined reference to `jack_set_process_callback'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0xb5): undefined reference to `jack_set_buffer_size_callback'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0xd3): undefined reference to `jack_set_sample_rate_callback'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0xf1): undefined reference to `jack_set_xrun_callback'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x113): undefined reference to `jack_on_shutdown'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x173): undefined reference to `jack_port_register'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x248): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x269): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.instream_open_jack+0x2b4): undefined reference to `jack_client_close'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `outstream_open_jack':
>           jack.c:(.text.outstream_open_jack+0x75): undefined reference to `jack_client_open'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x97): undefined reference to `jack_set_process_callback'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0xb5): undefined reference to `jack_set_buffer_size_callback'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0xd3): undefined reference to `jack_set_sample_rate_callback'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0xf1): undefined reference to `jack_set_xrun_callback'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x113): undefined reference to `jack_on_shutdown'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x173): undefined reference to `jack_port_register'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x248): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x269): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.outstream_open_jack+0x2b4): undefined reference to `jack_client_close'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `instream_process_callback':
>           jack.c:(.text.instream_process_callback+0x44): undefined reference to `jack_port_get_buffer'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `outstream_process_callback':
>           jack.c:(.text.outstream_process_callback+0x44): undefined reference to `jack_port_get_buffer'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `destroy_jack':
>           jack.c:(.text.destroy_jack+0x11): undefined reference to `jack_client_close'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `instream_start_jack':
>           jack.c:(.text.instream_start_jack+0x22): undefined reference to `jack_activate'
>           /usr/bin/ld: jack.c:(.text.instream_start_jack+0x4d): undefined reference to `jack_port_name'
>           /usr/bin/ld: jack.c:(.text.instream_start_jack+0x60): undefined reference to `jack_connect'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `outstream_start_jack':
>           jack.c:(.text.outstream_start_jack+0x22): undefined reference to `jack_activate'
>           /usr/bin/ld: jack.c:(.text.outstream_start_jack+0x4d): undefined reference to `jack_port_name'
>           /usr/bin/ld: jack.c:(.text.outstream_start_jack+0x60): undefined reference to `jack_connect'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `refresh_devices_bare':
>           jack.c:(.text.refresh_devices_bare+0x61): undefined reference to `jack_get_ports'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0xc8): undefined reference to `jack_port_by_name'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0xdc): undefined reference to `jack_port_flags'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0xe6): undefined reference to `jack_port_type'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0x7b6): undefined reference to `jack_free'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0x7de): undefined reference to `jack_free'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0x8b3): undefined reference to `jack_free'
>           /usr/bin/ld: jack.c:(.text.refresh_devices_bare+0x8de): undefined reference to `jack_free'
>           /usr/bin/ld: /tmp/rustcGyZt1N/liblibsoundio_sys-09bce83bdb19f39b.rlib(jack.c.o): in function `soundio_jack_init':
>           jack.c:(.text.soundio_jack_init+0x32): undefined reference to `jack_set_error_function'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x40): undefined reference to `jack_set_info_function'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x87): undefined reference to `jack_client_open'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0xa9): undefined reference to `jack_set_buffer_size_callback'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0xc7): undefined reference to `jack_set_sample_rate_callback'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0xe5): undefined reference to `jack_set_port_registration_callback'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x103): undefined reference to `jack_set_port_rename_callback'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x123): undefined reference to `jack_on_shutdown'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x136): undefined reference to `jack_get_buffer_size'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x148): undefined reference to `jack_get_sample_rate'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x15a): undefined reference to `jack_activate'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x33e): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x37d): undefined reference to `jack_client_close'
>           /usr/bin/ld: jack.c:(.text.soundio_jack_init+0x3dd): undefined reference to `jack_client_close'
>           collect2: error: ld returned 1 exit status
>           
>   = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
>   = note: use the `-l` flag to specify native libraries to link
>   = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
> 
> warning: `gm8emulator` (bin "gm8emulator") generated 25 warnings
> error: could not compile `gm8emulator` due to previous error; 25 warnings emitted

**Comment by TerminalHash** [comment]
I'm using pipewire-jack instead.

**Comment by viriw** [comment]
Both seem to provide `libjack.so`, so that's fine. I think you're not the first to have had this issue, pushed a fix just now, does that help? Might want to `cargo clean` before you try.

**Comment by TerminalHash** [comment]
Thanks for fix, it's working :D
