### ISSUE TITLE
Adding any extension package breaks a game

### ISSUE THREAD

**Issue by lab313ru** [OpenGMK/OpenGMK#138]
Hi,

I've decompiled a game using your decompiler, created executable, and the game works. But this game also uses some packages:
![image](https://github.com/OpenGMK/OpenGMK/assets/7189309/04ff4be9-dda1-4a0d-98a9-2650bf0d8311)

Adding them to the project breaks the game code and leads to the following while running it:
![image](https://github.com/OpenGMK/OpenGMK/assets/7189309/0e04f98c-6c8e-4d81-bd34-86b799cd97fa)

Could this happen due to incorrect decompilation?

**Comment by Adamcake** [comment]
It's possible but very unlikely. The error is in a script, which should have nothing to do with extension packages. 

It would be more likely that the error is caused by the game trying to load an invalid save file, and the fact that it happened after adding extensions is just a coincidence. Did the game create any save files, and what happens if you run the game after deleting all of them?

**Comment by lab313ru** [comment]
Yes, the game uses save files, but deleting them doesn't help.
Also, as I already wrote: Adding extension breaks the game, removing it again fixes it again.

**Comment by lab313ru** [comment]
Yeah, sure, thanks: [suteF.zip](https://github.com/OpenGMK/OpenGMK/files/12474701/suteF.zip)

**Comment by lab313ru** [comment]
I also forgot to say that opening the decompiled gmk in the Game Maker Studio 1 gives me an error about wrong room name, so I think it's somehow related to the project's corrupted structure.

**Comment by omicronrex** [comment]
This game doesn't use any extension packages. I've decompiled, and successfully recompiled it in GM 8.1.

**Comment by lab313ru** [comment]
But without these extensions I don't see some text messages (the first package?) after recompiling.

**Comment by omicronrex** [comment]
![image](https://github.com/OpenGMK/OpenGMK/assets/65692652/60500b91-fd1a-4614-9a18-fedc75e3e43c)
The game literally does Not use those packages. Adding them breaks the game.

**Comment by omicronrex** [comment]
Additionally, the game doesn't contain any message boxes in its code.

**Comment by Adamcake** [comment]
The reason text is invisible is because fonts can't be decompiled. You need to open the font assets, select a valid font from your system, save them, then build like that.
